apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: simplcash
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mysql-storage
              mountPath: /data/db
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: simplcash
spec:
  selector:
    app: mysql
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
